spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/water?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
            username: root
            password: root
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #Oracle需要打开注释
            #validation-query: SE多数据源的配置
    elasticsearch:
        bboss:
            elasticsearch:
                rest:
                    hostNames: 112.124.36.160:9200
                    dateFormat: yyyy.MM.dd
                    timeZone: Asia/Shanghai
                    showTemplate: true
                    discoverHost: false
            http:
                timeoutConnection: 5000
                timeoutSocket: 5000
                connectionRequestTimeout: 5000
                retryTime: 1
                maxLineLength: -1
                maxHeaderCount: 200
                maxTotal: 400
                defaultMaxPerRoute: 200
                soReuseAddress: false
                soKeepAlive: false
                timeToLive: 3600000
                keepAlive: 3600000
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost:1433;DatabaseName=renren_security
#      username: sa
#      password: 123456
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/renren_security
#      username: renren
#      password: 123456